### ISSUE TITLE
Root error?

### ISSUE THREAD

**Issue by betsybugaboo** [DreamCobbler/fiction-dl#11]
I've been getting this error the past few days with ff.net fics:

> ERROR:root:Failed to download page: "[URL]".
> ERROR:root:Failed to scan the story.

Is it something on my end? or has ff.net updated something? I've tried updating f-dl but it still keeps happening.

**Comment by DreamCobbler** [comment]
FF.net started protecting itself from bots, and it was able to identify f-dl as one. fiction-dl 1.8.0 uses [cloudscraper](https://pypi.org/project/cloudscraper/) to avoid being recognized to be a bot, so the problem ought to be solved in the newest release.
