### ISSUE TITLE
Story has 144 threadmarks

### ISSUE THREAD

**Issue by aguczam** [DreamCobbler/fiction-dl#15]
Some of them are hidden. You don't get hidden threadmarks. For example that https://forums.spacebattles.com/threads/this-wont-end-well-30k-isekai.587209/threadmarks . The result is 100 chapters. Command used: >fiction-dl https://forums.spacebattles.com/threads/this-wont-end-well-30k-isekai.587209/threadmarks

**Comment by DreamCobbler** [comment]
Should be fixed in 1.8.3.
