### ISSUE TITLE
[Feature] AO3 series support

### ISSUE THREAD

**Issue by laundmo** [DreamCobbler/fiction-dl#3]
Please support AO3 Series, to make downloading an entire series easier.
Adding to this, a feature to combine all stories downloaded into one document would be awsome (maybe a commandline flag that also works with providing a list?)

**Comment by DreamCobbler** [comment]
Done both in 1.6.0! A whole series can be now downloaded at once, using the URL of the series (for example: "fiction-dl https://archiveofourown.org/series/1390948" downloads all four stories belonging to the series). Same for collections.

Downloaded stories can be combined using the "-pack" command-line option; calling "fiction-dl -pack https://archiveofourown.org/series/1390948" will produce just one file of each file format. The file will contain the stories in the order they were published in. Works also with custom lists of stories (i.e. text files with a list of URLs), the order of the list is preserved there as well.
