### ISSUE TITLE
I had to install dreamy-utilities manually to get it working

### ISSUE THREAD

**Issue by Anangaya** [DreamCobbler/fiction-dl#6]
I installed this using pip but when I tried to download a story from HF I got error related to dreamy-utilities (don't remember exactly what but it worked perfectly after I installed dreamy-utilities using pip though. 
On a side note I was trying to scrape stories from HF when I found this on pypi. 
I'm new to programming and was trying to get an epub from the scraped html strings(chapters). Now that I found this I don't need to go through that anymore. Thanks for creating this tool. Really appreciate it.

**Comment by DreamCobbler** [comment]
*dreamy-utilities* was missing in the dependency list in 1.6.2. Fixed that in 1.6.3.
